// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OilChangeApp;

#nullable disable

namespace OilChangeApp.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20260310210330_BannedUsers")]
    partial class BannedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OilChangeApp.Admin", b =>
                {
                    b.Property<int>("Admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Admin_id"));

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nickname");

                    b.Property<string>("OilType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("oil_type");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Admin_id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("OilChangeApp.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("car_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("car_name");

                    b.Property<string>("car_num")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("car_num");

                    b.Property<string>("oil_type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("oil_type");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("OilChangeApp.Domain.Entities.BanedUsers", b =>
                {
                    b.Property<int>("BanedTgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BanedTgId"));

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExpiredDate");

                    b.HasKey("BanedTgId");

                    b.ToTable("BanedUsers");
                });

            modelBuilder.Entity("OilChangeApp.Domain.Entities.Oil_change", b =>
                {
                    b.Property<int>("Oil_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Oil_id"));

                    b.Property<DateTime>("Next_change_date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Next_change_date");

                    b.Property<long>("Next_change_km")
                        .HasColumnType("bigint")
                        .HasColumnName("Next_change_km");

                    b.Property<long>("Oil_liters")
                        .HasColumnType("bigint")
                        .HasColumnName("Oil_liters");

                    b.Property<string>("Oil_location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Oil_location");

                    b.Property<string>("Oil_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Oil_name");

                    b.Property<long>("Service_id")
                        .HasColumnType("bigint")
                        .HasColumnName("Service_id");

                    b.HasKey("Oil_id");

                    b.HasIndex("Service_id");

                    b.ToTable("Oil_change");
                });

            modelBuilder.Entity("OilChangeApp.Domain.Entities.Service_visit", b =>
                {
                    b.Property<long>("Service_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Service_id"));

                    b.Property<int>("Car_id")
                        .HasColumnType("int")
                        .HasColumnName("Car_id");

                    b.Property<DateTime>("Visit_date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Visit_date");

                    b.HasKey("Service_id");

                    b.HasIndex("Car_id");

                    b.ToTable("Service_visit");
                });

            modelBuilder.Entity("OilChangeApp.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("Telegram_id");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OilChangeApp.user_Car", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("Car_id");

                    b.HasKey("UserId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("User_Car");
                });

            modelBuilder.Entity("OilChangeApp.Domain.Entities.Oil_change", b =>
                {
                    b.HasOne("OilChangeApp.Domain.Entities.Service_visit", "Service_visit")
                        .WithMany()
                        .HasForeignKey("Service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service_visit");
                });

            modelBuilder.Entity("OilChangeApp.Domain.Entities.Service_visit", b =>
                {
                    b.HasOne("OilChangeApp.Car", "Car")
                        .WithMany()
                        .HasForeignKey("Car_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("OilChangeApp.user_Car", b =>
                {
                    b.HasOne("OilChangeApp.Car", "Car")
                        .WithMany("UserCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilChangeApp.User", "User")
                        .WithMany("UserCars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OilChangeApp.Car", b =>
                {
                    b.Navigation("UserCars");
                });

            modelBuilder.Entity("OilChangeApp.User", b =>
                {
                    b.Navigation("UserCars");
                });
#pragma warning restore 612, 618
        }
    }
}
